// demos/svelte/src/HiddenLogin.svelte
<script lang="ts">
  import { continueWalkthroughAfterLogin, HIDDEN_LOGIN_PATH, isValidDemoEmail, setDemoOwner } from '../../shared/hidden-login';
  import GitHubFooter from './GitHubFooter.svelte';

  let email = $state('');
  let pass = $state('');
  let error = $state<string | null>(null);

  function onSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (!isValidDemoEmail(email) || !pass.trim()) {
      error = 'Enter a valid email and a password.';
      return;
    }
    setDemoOwner(true);
    continueWalkthroughAfterLogin();
    window.location.assign('/');
  }
</script>

<main class="login" data-demo="login-card">
  <p class="kicker">Hidden login</p>
  <p class="lede">{HIDDEN_LOGIN_PATH}</p>
  <h1>Access hidden login</h1>
  <p class="lede">This URL is not linked from the home page. Any valid email and password works. No real session.</p>
  <form data-demo="hidden-login-form" onsubmit={onSubmit}>
    <label>
      Email
      <input type="email" required autocomplete="username" bind:value={email} />
    </label>
    <label>
      Password
      <input type="password" required autocomplete="current-password" bind:value={pass} />
    </label>
    {#if error}
      <p class="err">{error}</p>
    {/if}
    <button class="primary" type="submit">Sign in</button>
  </form>
  <p><a href="/">← Back</a></p>
  <GitHubFooter />
</main>

// components/demo/hidden-login.tsx
'use client';

import { useState, type FormEvent } from 'react';
import { isValidDemoEmail, setDemoOwner } from '@/lib/demo-owner';

export function HiddenLoginForm({
  hideSubmit = false,
  onSuccess,
}: {
  hideSubmit?: boolean;
  onSuccess?: () => void;
}) {
  const [email, setEmail] = useState('');
  const [pass, setPass] = useState('');
  const [error, setError] = useState<string | null>(null);

  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!isValidDemoEmail(email) || !pass.trim()) {
      setError('Enter a valid email and a password.');
      return;
    }
    setError(null);
    setDemoOwner(true);
    onSuccess?.();
  };

  return (
    <form
      data-demo="hidden-login-form"
      className="space-y-3"
      onSubmit={onSubmit}
    >
      <div className="space-y-1.5">
        <label htmlFor="hidden-login-email" className="text-sm text-zinc-300">
          Email
        </label>
        <input
          id="hidden-login-email"
          type="email"
          required
          autoComplete="username"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          className="w-full rounded-md border border-white/15 bg-zinc-950 px-3 py-2.5 text-zinc-50 outline-none focus:border-amber-400"
        />
      </div>
      <div className="space-y-1.5">
        <label htmlFor="hidden-login-pass" className="text-sm text-zinc-300">
          Password
        </label>
        <input
          id="hidden-login-pass"
          type="password"
          required
          autoComplete="current-password"
          value={pass}
          onChange={(event) => setPass(event.target.value)}
          className="w-full rounded-md border border-white/15 bg-zinc-950 px-3 py-2.5 text-zinc-50 outline-none focus:border-amber-400"
        />
      </div>
      {error && <p className="text-sm text-rose-300">{error}</p>}
      {!hideSubmit && (
        <button
          type="submit"
          className="w-full rounded-full bg-amber-400 px-4 py-2.5 text-sm font-medium text-zinc-950 hover:bg-amber-300"
        >
          Sign in
        </button>
      )}
    </form>
  );
}
